client/urls.py
from .views import *
from django.urls import path

app_name = 'clients'

urlpatterns = [
   path('', IndexView.as_view(), name = 'index'),
   path('product/<int:product_id>/', ProductPageView.as_view(), name='productview'),
   path('categorylist/<str:slug>/', CategoryList.as_view(), name='categorylist'),
   path('AddtoCart/<int:product_id>/', AddToCart, name='addtocart'),
   path('viewcart/', view_cart, name='view_cart'),
   path('remove_from_cart/<int:item_id>/', Remove_From_Cart, name='remove_cart'),
   path('update-cart/', Update_Cart, name='update_cart')
   
   
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from catalogue.views import getCategory



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls')),
    # path('accounts/', include("django.contrib.auth.urls")),
    # path('', getCategory, name = "get-category"),
    path('accounts/', include('accounts.urls')),
    path('api/catalogue/', include('catalogue.api.urls')),
    
    path('dashboard/', include("dashboard.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

client/models.py
from django.db import models
from accounts.models import User
from catalogue.models import Product

class Cart(models.Model):
    user = models.OneToOneField(User, related_name = 'cart_user', on_delete = models.CASCADE )
    
    @classmethod
    def get_Total_count(cls, user):
        count = 0
        for i in CartItem.objects.filter(cart__user = user):
            count += i.quantity
        return count

    @classmethod
    def get_total(cls, user):
        total = 0
        for i in CartItem.objects.filter(cart__user = user):
            total += i.quantity * i.product.price
        return total
    
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name = 'cart_item', on_delete = models.CASCADE)
    product = models.ForeignKey(Product, related_name = 'cart_product', on_delete = models.CASCADE)
    quantity = models.IntegerField(default = 0)
    
class Order(models.Model):
    PENDING = 'Pending'
    PROCESSING = 'Processing'
    DELIVERED = 'Delivered'

    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (PROCESSING, 'Processing'),
        (DELIVERED, 'Delivered'),
    ]
    user = models.OneToOneField(User, related_name = 'user_order', on_delete = models.CASCADE )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    total_price = models.DecimalField(max_digits=15, decimal_places = 2, default = 0.0)
    status = models.CharField(max_length=20, choices = STATUS_CHOICES, default = PENDING)
    
    def calculate_total(self):
        total = 0
        for item in self.order_items.all():
            total += item.calculate_subtotal()
            self.total_price = total
            self.save()
        
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='order_items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_products', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    def calculate_subtotal(self):
        return self.quantity * self.product.price

client/views.py
from typing import Any
from django.shortcuts import render,get_object_or_404
from django.shortcuts import render, redirect
from accounts.models import User
from django.views.generic import TemplateView
from .models import Cart, CartItem
from catalogue.models import (Category,
                              Product,
                              Banner,Brand)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
# Create your views here.

class BaseView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super(BaseView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        context['product'] = Product.objects.all()
        if self.request.user.is_authenticated:
            # cart = get_object_or_404(Cart, user = self.request.user)
            # context['cart'] = cart
            context['cart_count'] = Cart.get_Total_count(self.request.user)
            context['total'] = Cart.get_total(self.request.user)
            context['cart_item'] = CartItem.objects.filter(cart__user = self.request.user)
        else:
            context['cart_item'] = []
            context['cart_count'] = 0
        
        
        return context
        # return super().get_context_data(**kwargs)

class IndexView(BaseView):  
    template_name = 'client/index.html'
    
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['banner'] = Banner.objects.all()
        context['popular_category'] = Category.objects.filter(is_popular = True)
        context['is_featured'] = Product.objects.filter(is_featured= True)
        return self.render_to_response(context)
    
    
    

class ProductPageView(BaseView):
    template_name = 'client/index/productview.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        
        product_id = kwargs.get('product_id')
        context['product'] = get_object_or_404(Product, pk=product_id)
        return render(request, self.template_name, context)


class CategoryList(BaseView):
    template_name = 'client/index/categorylist.html'
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        context['category_brand'] = Brand.objects.filter(product_brand__category__slug = kwargs.get('slug')).distinct()
        sort_by = request.GET.get('sortby')
        brand_list = request.GET.getlist('brands')
        context['brand_list'] = brand_list
        context['sort_by'] = sort_by
        if sort_by:
            sort_by = '-'+sort_by
            product = Product.objects.filter(category__slug = kwargs.get('slug')).order_by(sort_by)
            if not len(brand_list) == 0:
                product = product.filter(brands_id__in = brand_list)
            # context['product'] = product
        else:
            product = Product.objects.filter(category__slug = kwargs.get('slug'))
            if not len(brand_list) == 0:
                product = product.filter(brands_id__in = brand_list) 
        paginator = Paginator(product, 2)
        try:
           page = request.GET.get('page')
           product = paginator.get_page(page)
        except PageNotAnInteger:
           product = paginator.get_page(1)
        except EmptyPage:
           product = paginator.get_page(paginator.num_pages)
        context['product'] = product
        return render(request, self.template_name, context)

@login_required(login_url = '/accounts/login')
def AddToCart(request, product_id):
    if request.method == 'POST':
        quantity = request.POST.get('quantity')
        try: 
            cart = Cart.objects.get(user = request.user)
        except:
            cart = Cart.objects.create(user = request.user)
            print(cart)
    
        product = get_object_or_404(Product, id = product_id)

        if CartItem.objects.filter(cart = cart, product_id = product_id).exists():
            item = CartItem.objects.get(cart = cart, product_id = product_id)
            quantity = item.quantity + int(quantity)
            item.quantity = quantity
            item.save()
        
        else:
            item = CartItem.objects.create(cart = cart,
                product = product, quantity = quantity)
    
    category_slug = item.product.category.slug
    messages.success(request,'Item added successfully!!')
    return redirect('clients:categorylist', slug = category_slug)

def view_cart(request):
    # Retrieve cart items for the current user
    user_cart_items = CartItem.objects.filter(cart__user=request.user)

    # Calculate total and other necessary information if needed
    total_items = user_cart_items.count()
    total_amount = 0
    for cart_item in user_cart_items:  
        cart_item.total_cost = cart_item.quantity * cart_item.product.price
        total_amount += cart_item.total_cost
    context = {
        'cart_items': user_cart_items,
        'total_items': total_items,
        'total_amount': total_amount,
    }

    return render(request, 'client/index/viewcart.html', context)

def Remove_From_Cart(request, item_id):
    item = CartItem.objects.get(id=item_id)
    item.delete()
    messages.success(request,'Item removed successfully!!')
    return redirect('clients:view_cart')

@require_POST
def Update_Cart(request):
    try:
        cart = request.user.cart_user  # Access the Cart object associated with the current user
    except Cart.DoesNotExist:
        # Handle the case where the user does not have a cart
        return redirect('clients:productview')
    updated_items = 0
    for cart_item in cart.cart_item.all():
        quantity_key = f'quantity_{cart_item.id}'
        if quantity_key in request.POST:
            cart_item.quantity = request.POST.get(quantity_key)
            cart_item.save()
            updated_items += 1
    if updated_items > 0:
        messages.success(request,f'{updated_items} item(s) updated successfully.')
    else:
        messages.info(request, 'No items were updated.')
    return redirect('clients:view_cart')

templates/client/index/productview.html
{% extends "client/base.html" %}
{%block content%}


<main class="main">

    <div class="page-content">
        <div class="container">
            <div class="product-details-top">
                <div class="row">
                    <div class="col-md-6">
                        <div class="product-gallery product-gallery-vertical">
                            <div class="row">
                                
                                <figure class="product-main-image">
                                    <img id="product-zoom" src="{{product.image.url}}" data-zoom-image="assets/images/products/single/1-big.jpg" alt="product image">

                                    <a href="#" id="btn-product-gallery" class="btn-product-gallery">
                                        <i class="icon-arrows"></i>
                                    </a>
                                </figure><!-- End .product-main-image -->

                                <div id="product-zoom-gallery" class="product-image-gallery">
                                    <a class="product-gallery-item active" href="#" data-image="assets/images/products/single/1.jpg" data-zoom-image="assets/images/products/single/1-big.jpg">
                                        <img src="{{product.image.url}}" alt="product side">
                                    </a>

                                    <a class="product-gallery-item" href="#" data-image="assets/images/products/single/2.jpg" data-zoom-image="assets/images/products/single/2-big.jpg">
                                        <img src="{{product.image2.url}}" alt="product cross">
                                    </a>

                                    <a class="product-gallery-item" href="#" data-image="assets/images/products/single/3.jpg" data-zoom-image="assets/images/products/single/3-big.jpg">
                                        <img src="{{product.image3.url}}" alt="product with model">
                                    </a>

                                    <a class="product-gallery-item" href="#" data-image="assets/images/products/single/4.jpg" data-zoom-image="assets/images/products/single/4-big.jpg">
                                        <img src="{{product.image4.url}}" alt="product back">
                                    </a>
                                </div><!-- End .product-image-gallery -->
                            </div><!-- End .row -->
                        </div><!-- End .product-gallery -->
                    </div><!-- End .col-md-6 -->

                    <div class="col-md-6">
                        <div class="product-details">
                            <h1 class="product-title">{{product.name}}</h1><!-- End .product-title -->

                            <div class="ratings-container">
                                <div class="ratings">
                                    <div class="ratings-val" style="width: 80%;"></div><!-- End .ratings-val -->
                                </div><!-- End .ratings -->
                                <a class="ratings-text" href="#product-review-link" id="review-link">( 2 Reviews )</a>
                            </div><!-- End .rating-container -->

                            <div class="product-price">
                                {{product.price}}
                            </div><!-- End .product-price -->

                            <div class="product-content">
                                <p>{{product.description}} </p>
                            </div><!-- End .product-content -->

                            <div class="details-filter-row details-row-size">
                                <label>Color:{{product.color}}</label>

                                

                            <div class="details-filter-row details-row-size">
                                <label for="size">Size:</label>
                                <div class="select-custom">
                                    <select name="size" id="size" class="form-control">
                                        <option value="#" selected="selected">Select a size</option>
                                        <option value="s">{{product.size}}</option>
                                    </select>
                                </div><!-- End .select-custom -->


                            <div class="details-filter-row details-row-size">
                                <label for="qty">Qty:{{product.quantity}}</label>
                                <div class="product-details-quantity">
                                    <input type="number" id="qty" class="form-control" value="1" min="1" max="10" step="1" data-decimals="0" required>
                                </div><!-- End .product-details-quantity -->
                            </div><!-- End .details-filter-row -->

                            <div class="product-details-action">
                                <a href="#" class="btn-product btn-cart"><span>add to cart</span></a>

                                <div class="details-action-wrapper">
                                    <a href="#" class="btn-product btn-wishlist" title="Wishlist"><span>Add to Wishlist</span></a>
                                    <a href="#" class="btn-product btn-compare" title="Compare"><span>Add to Compare</span></a>
                                </div><!-- End .details-action-wrapper -->
                            </div><!-- End .product-details-action -->

                            <div class="product-details-footer">
                                <div class="product-cat">
                                    <span>Category:</span>
                                    <a href="#">{{product.category.name}}</a>,
                                </div><!-- End .product-cat -->

                            </div><!-- End .product-details-footer -->
                        </div><!-- End .product-details -->
                    </div><!-- End .col-md-6 -->
                </div><!-- End .row -->
            </div><!-- End .product-details-top -->

            <div class="product-details-tab">
                <ul class="nav nav-pills justify-content-center" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="product-desc-link" data-toggle="tab" href="#product-desc-tab" role="tab" aria-controls="product-desc-tab" aria-selected="true">Description</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="product-desc-tab" role="tabpanel" aria-labelledby="product-desc-link">
                        <div class="product-desc-content">
                            <h3>Product Information</h3>
                            <p>{{product.description}} </p>
                        </div><!-- End .product-desc-content -->
                    </div><!-- .End .tab-pane -->
                    
                </div><!-- End .tab-content -->
            </div><!-- End .product-details-tab -->

           {%endblock%}

templates/client/index/viewcart.html
{%extends 'client/base.html'%}


{%block content%}
<main class="main">
    <div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        <div class="container">
            <h1 class="page-title">Shopping Cart<span>Shop</span></h1>
        </div><!-- End .container -->
    </div><!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Shop</a></li>
                <li class="breadcrumb-item active" aria-current="page">Shopping Cart</li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
            {%if messages%}
        <div class="cart">
                {%for message in messages%}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
            
            <div class="container">
                
                <div class="row">
                    
                    <div class="col-lg-9">
                        <form method = 'POST' action = "{%url 'clients:update_cart' %}" id="update-cart-form">
                            {% csrf_token %}
                        <table class="table table-cart table-mobile">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                                {%for cart_item in cart_items%}
                                <tr>
                                    <td class="product-col">
                                        <div class="product">
                                            <figure class="product-media">
                                                <a href="#">
                                                    <img src="{{cart_item.product.image.url}}" alt="Product image">
                                                </a>
                                            </figure>

                                            <h3 class="product-title">
                                                <a href="#">{{cart_item.product.name}}</a>
                                            </h3><!-- End .product-title -->
                                        </div><!-- End .product -->
                                    </td>
                                    <td class="price-col">{{cart_item.product.price}}</td>
                                    <td class="quantity-col">
                                        <div class="cart-product-quantity">
                                            <input type="number" class="form-control" name="quantity_{{ cart_item.id }}" value="{{cart_item.quantity}}" min="1" max="10" step="1" data-decimals="0" required>
                                        </div><!-- End .cart-product-quantity -->
                                    </td>
                                    <td class="total-col">{{cart_item.total_cost}}</td>
                                    <td class="remove-col"><a href="{%url 'clients:remove_cart' cart_item.id%}" class="btn-remove"><i class="icon-close"></i></button></td>
                                </tr>
                                {%endfor%}
                            </tbody>
                        </table><!-- End .table table-wishlist -->

                        <div class="cart-bottom">
                            

                            <button type = "submit" class="btn btn-outline-dark-2"><span>UPDATE CART</span><i class="icon-refresh"></i></button>
                        </div><!-- End .cart-bottom -->
                    </form>
                    </div><!-- End .col-lg-9 -->
                
                    <aside class="col-lg-3">
                        <div class="summary summary-cart">
                            <h3 class="summary-title">Cart Total</h3><!-- End .summary-title -->

                            <table class="table table-summary">
                                <tbody>
                                    <tr class="summary-subtotal">
                                        <td>Subtotal:</td>
                                        <td>RS.{{total_amount}}</td>
                                    </tr><!-- End .summary-subtotal -->
                                    <tr class="summary-shipping">
                                        <td>Shipping:</td>
                                        <td>&nbsp;</td>
                                    </tr>

                                    <tr class="summary-shipping-row">
                                        <td>
                                            <div class="custom-control custom-radio">
                                                <input type="radio" id="free-shipping" name="shipping" class="custom-control-input">
                                                <label class="custom-control-label" for="free-shipping">Free Shipping</label>
                                            </div><!-- End .custom-control -->
                                        </td>
                                        <td>$0.00</td>
                                    </tr><!-- End .summary-shipping-row -->

                                    <tr class="summary-shipping-row">
                                        <td>
                                            <div class="custom-control custom-radio">
                                                <input type="radio" id="standart-shipping" name="shipping" class="custom-control-input">
                                                <label class="custom-control-label" for="standart-shipping">Standart:</label>
                                            </div><!-- End .custom-control -->
                                   .     </td>
                                        <td>$10.00</td>
                                    </tr><!-- End .summary-shipping-row -->


                                    <tr class="summary-shipping-estimate">
                                        <td>Estimate for Your Country<br> <a href="dashboard.html">Change address</a></td>
                                        <td>&nbsp;</td>
                                    </tr><!-- End .summary-shipping-estimate -->

                                    <tr class="summary-total">
                                        <td>Total:</td>
                                        <td>Rs.{{total_amount}}</td>
                                    </tr><!-- End .summary-total -->
                                </tbody>
                            </table><!-- End .table table-summary -->

                            <a href="checkout.html" class="btn btn-outline-primary-2 btn-order btn-block">PROCEED TO CHECKOUT</a>
                        </div><!-- End .summary -->

                        <a href="{%url 'clients:index'%}" class="btn btn-outline-dark-2 btn-block mb-3"><span>CONTINUE SHOPPING</span><i class="icon-refresh"></i></a>
                    </aside><!-- End .col-lg-3 -->
                </div><!-- End .row -->
            </div><!-- End .container -->
        </div><!-- End .cart -->
    </div><!-- End .page-content -->
</main><!-- End .main -->
{%endblock%}