client/urls.py
from .views import *
from django.urls import path

app_name = 'clients'

urlpatterns = [
   path('', IndexView.as_view(), name = 'index'),
   path('product/<int:product_id>/', ProductPageView.as_view(), name='productview'),
   path('categorylist/<str:slug>/', CategoryList.as_view(), name='categorylist'),
   path('AddtoCart/<int:product_id>/', AddToCart, name='addtocart'),
   path('viewcart/', view_cart, name='view_cart'),
   path('remove_from_cart/<int:item_id>/', Remove_From_Cart, name='remove_cart'),
   path('update-cart/', Update_Cart, name='update_cart')
   
   
]

dashboard/urls.py
# from .views import mainDashboard
from .views import *
from django.urls import path

app_name = 'dashboard'

urlpatterns = [
    path('', mainDashboard, name='main-dashboard'),
    path('category-create/', createCategory,  name = 'category-create'),
    path('category-update/<int:pk>/', updateCategory, name = "category-update"),
    path('category-list/', listCategory, name = 'category-list'),
    path('product-list/', ProductList.as_view(), name = 'product-list' ),
    path('product-create/', ProductCreate.as_view(), name = 'product-create'),
    path('product-update/<int:pk>/', ProductUpdate.as_view(), name = "product-update"),
    path('product-delete/<int:pk>/', ProductDelete.as_view(), name = "product-delete"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from catalogue.views import getCategory



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls')),
    # path('accounts/', include("django.contrib.auth.urls")),
    # path('', getCategory, name = "get-category"),
    path('accounts/', include('accounts.urls')),
    path('api/catalogue/', include('catalogue.api.urls')),
    
    path('dashboard/', include("dashboard.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/custom_dashboard/category/category-list.html
{%extends "custom_dashboard/base.html"%}

{%block content%}
<div class="container-xxl flex-grow-1 container-p-y">
    <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Tables /</span> Basic Tables</h4>
    
    
    <!-- Basic Bootstrap Table -->
    <div class="card">
      <h5 class="card-header">Table Basic</h5>
      <div class="table-responsive text-nowrap">
        <div class="demo-inline-spacing">
            <a href={%url "dashboard:category-create"%}><button type="button" class="btn btn-primary">Create Category</button></a>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Slug</th>
              <th>Display Order</th>
              <th>Created At</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody class="table-border-bottom-0">
            {%for cat in category%}
            <tr>
              <td><i class="fab fa-angular fa-lg text-danger me-3"></i> <strong>{{cat.name|title}}</strong></td>
              <td>{{cat.slug}}</td>
              <td>{{cat.display_order}}</td>
              <td>
                {{cat.created_at}}
              </td>
              <td>
                <span class="badge bg-label-primary me-1"><div class="demo-inline-spacing">
                <a href={%url "dashboard:category-update" cat.id %}><button type="button" class="btn btn-primary">Update</button></a>
                </div>
            </span></td>

            </tr>
            {%endfor%}
           
          </tbody>
        </table>
      </div>
    </div>
   
    
  </div>
{%endblock%}

templates/custom_dashboard/category/category-update.html
{%extends 'custom_dashboard/base.html'%}
{% load crispy_forms_tags %}


{%block content%}
<div class="container-xxl flex-grow-1 container-p-y">
           <form method= 'post' action = "{%url 'dashboard:category-update' pk%}">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" value = 'Update category'>
           </form>
        </div>
{%endblock%}

templates/custom_dashboard/category/category_create.html
{%extends 'custom_dashboard/base.html'%}
{% load crispy_forms_tags %}


{%block content%}
<div class="container-xxl flex-grow-1 container-p-y">
           <form method= 'post' action = "{%url 'dashboard:category-create'%}">
                    {% csrf_token %}
                    {{form|crispy}}
                    <input type="submit" value = 'create category'>
           </form>
        </div>
{%endblock%}