client/urls.py
from .views import *
from django.urls import path

app_name = 'clients'

urlpatterns = [
   path('', IndexView.as_view(), name = 'index'),
   path('product/<int:product_id>/', ProductPageView.as_view(), name='productview'),
   path('categorylist/<str:slug>/', CategoryList.as_view(), name='categorylist'),
   path('AddtoCart/<int:product_id>/', AddToCart, name='addtocart'),
   path('viewcart/', view_cart, name='view_cart'),
   path('remove_from_cart/<int:item_id>/', Remove_From_Cart, name='remove_cart'),
   path('update-cart/', Update_Cart, name='update_cart')
   
   
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from catalogue.views import getCategory



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls')),
    # path('accounts/', include("django.contrib.auth.urls")),
    # path('', getCategory, name = "get-category"),
    path('accounts/', include('accounts.urls')),
    path('api/catalogue/', include('catalogue.api.urls')),
    
    path('dashboard/', include("dashboard.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/client/index/partial/banner.html
 <div class="intro-slider-container mb-5">
    <div class="intro-slider owl-carousel owl-theme owl-nav-inside owl-light" data-toggle="owl" 
        data-owl-options='{
            "dots": true,
            "nav": false, 
            "responsive": {
                "1200": {
                    "nav": true,
                    "dots": false
                }
            }
        }'> 
        {% for b in banner%}
        <div class="intro-slide" style="background-image: url('{{b.image.url}}')">
            <div class="container intro-content">
                <div class="row justify-content-end">
                    <div class="col-auto col-sm-7 col-md-6 col-lg-5">
                        <h3 class="intro-subtitle text-third">Deals and Promotions</h3><!-- End .h3 intro-subtitle -->
                        <h1 class="intro-title">{{b.name}}</h1>
                        <h1 class="intro-title">Dre Studio 3</h1><!-- End .intro-title -->

                        <div class="intro-price">
                            <sup class="intro-old-price">$349,95</sup>
                            <span class="text-third">
                                $279<sup>.99</sup>
                            </span>
                        </div><!-- End .intro-price -->

                        <a href="category.html" class="btn btn-primary btn-round">
                            <span>Shop More</span>
                            <i class="icon-long-arrow-right"></i>
                        </a>
                    </div><!-- End .col-lg-11 offset-lg-1 -->
                </div><!-- End .row -->
            </div><!-- End .intro-content -->
        </div><!-- End .intro-slide -->
        {% endfor %}
    </div><!-- End .intro-slider owl-carousel owl-simple -->
    <span class="slider-loader"></span><!-- End .slider-loader -->
</div><!-- End .intro-slider-container -->

templates/client/index/partial/newarrival.html
<div class="container new-arrivals">
    <div class="heading heading-flex mb-3">
        <div class="heading-left">
            <h2 class="title">New Arrivals</h2><!-- End .title -->
        </div><!-- End .heading-left -->

       
    </div><!-- End .heading -->

    <div class="tab-content tab-content-carousel just-action-icons-sm">
        <div class="tab-pane p-0 fade show active" id="new-all-tab" role="tabpanel" aria-labelledby="new-all-link">
            <div class="owl-carousel owl-full carousel-equal-height carousel-with-shadow" data-toggle="owl" 
                data-owl-options='{
                    "nav": true, 
                    "dots": true,
                    "margin": 20,
                    "loop": false,
                    "responsive": {
                        "0": {
                            "items":2
                        },
                        "480": {
                            "items":2
                        },
                        "768": {
                            "items":3
                        },
                        "992": {
                            "items":4
                        },
                        "1200": {
                            "items":5
                        }
                    }
                }'>
{%for p in product%}
                <div class="product product-2">
                    <figure class="product-media">
                        <span class="product-label label-circle label-top">Top</span>
                        <a href="{%url 'clients:productview' product_id=p.id%}">
                            <img src="{{p.image.url}}" alt="Product image" class="product-image">
                        </a>

                        <div class="product-action-vertical">
                            <a href="#" class="btn-product-icon btn-wishlist" title="Add to wishlist"></a>
                        </div><!-- End .product-action -->

                        <div class="product-action">
                            <form action="{%url 'clients:addtocart' p.id%}" method="POST">
                                {% csrf_token %}
                                <div class="quantity-container">
                                <input type="number" name="quantity" value="1" min="1" required>
                            </div>

                            <button type = "submit" class="btn-product btn-cart"><span>add to cart</span></a>
                            </form>
                        </div><!-- End .product-action -->
                    </figure><!-- End .product-media -->

                    <div class="product-body">
                        <div class="product-cat">
                            <a href="#">{{p.category.name}}</a>
                        </div><!-- End .product-cat -->
                        <h3 class="product-title"><a href="product.html">{{p.name}}</a></h3><!-- End .product-title -->
                        <div class="product-price">
                            RS. {{p.price}}
                        </div><!-- End .product-price -->
                        <div class="product-quantity">
                            Quantity {{p.quantity}}
                        </div><!-- End .product-quantity -->
                        <div class="product-description">
                             {{p.description}}
                        </div><!-- End .product-description -->
                        <div class="ratings-container">
                            <div class="ratings">
                                <div class="ratings-val" style="width: 100%;"></div><!-- End .ratings-val -->
                            </div><!-- End .ratings -->
                            <span class="ratings-text">( 4 Reviews )</span>
                        </div><!-- End .rating-container -->
                    </div><!-- End .product-body -->
                </div><!-- End .product -->
{%endfor%}

            </div><!-- End .owl-carousel -->
        </div><!-- .End .tab-pane -->
    </div><!-- End .tab-content -->
</div><!-- End .container -->

templates/client/index/partial/popular_category.html
<div class="container">
    <h2 class="title text-center mb-4">Explore Popular Categories</h2><!-- End .title text-center -->
    
    <div class="cat-blocks-container">
        <div class="row">
            {%for p in popular_category %}
            <div class="col-6 col-sm-4 col-lg-2">
                <a href="{%url 'clients:productview' p.id%}" class="cat-block">
                    <figure>
                        <span>
                            <img src="{{p.image.url}}" alt="{{p.name}}">
                        </span>
                    </figure>

                    <h3 class="cat-block-title">{{p.name|title}}</h3><!-- End .cat-block-title -->
                </a>
            </div><!-- End .col-sm-4 col-lg-2 -->
            {%endfor%}
        </div><!-- End .row -->
    </div><!-- End .cat-blocks-container -->
</div><!-- End .container -->

templates/client/index/partial/trending_product.html
<div class="bg-light pt-5 pb-6">
    <div class="container trending-products">
        <div class="heading heading-flex mb-3">
            <div class="heading-left">
                <h2 class="title">Trending Products</h2><!-- End .title -->
            </div><!-- End .heading-left -->

           <div class="heading-right">
                <ul class="nav nav-pills nav-border-anim justify-content-center" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="trending-top-link" data-toggle="tab" href="#trending-top-tab" role="tab" aria-controls="trending-top-tab" aria-selected="true">Top Rated</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="trending-best-link" data-toggle="tab" href="#trending-best-tab" role="tab" aria-controls="trending-best-tab" aria-selected="false">Best Selling</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="trending-sale-link" data-toggle="tab" href="#trending-sale-tab" role="tab" aria-controls="trending-sale-tab" aria-selected="false">On Sale</a>
                    </li>
                </ul>
           </div><!-- End .heading-right -->
        </div><!-- End .heading -->



            <div class="col-xl-4-5col">
                <div class="tab-content tab-content-carousel just-action-icons-sm">
                    <div class="tab-pane p-0 fade show active" id="trending-top-tab" role="tabpanel" aria-labelledby="trending-top-link">
                        <div class="owl-carousel owl-full carousel-equal-height carousel-with-shadow" data-toggle="owl" 
                            data-owl-options='{
                                "nav": true, 
                                "dots": false,
                                "margin": 20,
                                "loop": false,
                                "responsive": {
                                    "0": {
                                        "items":2
                                    },
                                    "480": {
                                        "items":2
                                    },
                                    "768": {
                                        "items":3
                                    },
                                    "992": {
                                        "items":4
                                    }
                                }
                            }'>
                            {%for p in is_featured %}
                            
                            <div class="product product-2">
                                <figure class="product-media">
                                    <span class="product-label label-circle label-top">Top</span>
                                    <a href="{% url 'clients:productview' product_id=p.id %}">
                                        <img src="{{p.image.url}}" alt="{{p.name}}" class="product-image">
                                    </a>

                                    <div class="product-action-vertical">
                                        <a href="#" class="btn-product-icon btn-wishlist" title="Add to wishlist"></a>
                                    </div><!-- End .product-action -->

                                    <div class="product-action">
                                        <a href="" class="btn-product btn-cart" title="Add to cart"><span>add to cart</span></a>
                                        <a href="{% url 'clients:productview' product_id=p.id %}" class="btn-product btn-quickview" title="Quick view"><span>quick view</span></a>
                                    </div><!-- End .product-action -->
                                </figure><!-- End .product-media -->

                                <div class="product-body">
                                    <div class="product-cat">
                                        <a href="#">{{p.category.name}}</a>
                                    </div><!-- End .product-cat -->
                                    <h3 class="product-title"><a href="product.html">{{p.name|title}}</a></h3><!-- End .product-title -->
                                    <div class="product-price">
                                        Rs.{{p.price}}
                                    </div><!-- End .product-price -->
                                    <div class="product-quantity">
                                        quantity {{p.quantity}}
                                    </div><!-- End .product-quantity -->
                                    <div class="product-color">
                                        {{p.color}}
                                    </div><!-- End .product-color -->
                                    <div class="product-nav ">
                                    <h5 class="product-description">{{p.description}}</h5><!-- End .product-description -->
                                        
                                    </div><!-- End .product-nav -->
                                </div><!-- End .product-body -->
                            </div><!-- End .product -->
                            {%endfor%}


                        </div><!-- End .owl-carousel -->
                    </div><!-- .End .tab-pane -->
                </div><!-- End .tab-content -->
            </div><!-- End .col-xl-4-5col -->
        </div><!-- End .row -->
    </div><!-- End .container -->
</div><!-- End .bg-light pt-5 pb-6 -->